export const QKeys = {
  GET_USERS: 'GET_USERS',
  GET_USER_BY_INDEX: 'GET_USER_BY_INDEX',
  GET_USER: 'GET_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
};
